name: Run .NET Code Analysis WF
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '3.1.x'
      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1
      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1
      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1        
      - name: Run NuGet restore
        run: dotnet restore dotnet-core-hello-world.csproj
      - name: Build the project
        run: dotnet build dotnet-core-hello-world.csproj
      - name: Say Completed
        run: 'echo "Code Analysis Completed!"'
