name: Run .NET Code Analysis WF
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get Your Code
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1        
      - name: Run NuGet restore
        run: dotnet restore .\dotnet-core-hello-world.sln
      - name: MegaLinter
        uses: oxsecurity/megalinter@v7.13.0
        id: code-analysis
        with:
          solution: dotnet-core-hello-world.sln
          build-breaking: true
          all-categories: all
      - name: Say Completed
        run: 'echo "Code Analysis Completed!"'
